[[language]]
name = "python"
language-servers = ["ruff", "pyright"]
auto-format = true

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]
