[[language]]
name = "python"
language-servers = ["pyright"]
auto-format = true

[language.formatter]
command = "black"
args = ["-", "--quiet"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
