#app_launch_prefix = 'uwsm app -- '
as_window = false
close_when_open = false
disable_click_to_close = false
force_keyboard_focus = false
hotreload_theme = false
locale = ''
monitor = ''
terminal_title_flag = ''
theme = 'catppuccin-frappe'
timeout = 0.0

[activation_mode]
labels = 'jkl;asdf'

[builtins]
[builtins.ai]
icon = 'help-browser'
name = 'ai'
placeholder = 'AI'
switcher_only = true
weight = 5.0

[builtins.ai.anthropic]
[[builtins.ai.anthropic.prompts]]
label = 'General Assistant'
max_tokens = 1000.0
model = 'claude-3-5-sonnet-20241022'
prompt = 'You are a helpful general assistant. Keep your answers short and precise.'
temperature = 1.0

[builtins.applications]
context_aware = true
hide_actions_with_empty_query = true
name = 'applications'
placeholder = 'Applications'
prioritize_new = true
refresh = true
show_generic = true
show_icon_when_single = true
show_sub_when_single = true
weight = 5.0

[builtins.applications.actions]
enabled = true
hide_category = false
hide_without_query = true

[builtins.bookmarks]
icon = 'bookmark'
name = 'bookmarks'
placeholder = 'Bookmarks'
switcher_only = true
weight = 5.0

[[builtins.bookmarks.entries]]
keywords = ['walker', 'github']
label = 'Walker'
url = 'https://github.com/abenz1267/walker'

[builtins.calc]
icon = 'accessories-calculator'
min_chars = 4.0
name = 'calc'
placeholder = 'Calculator'
require_number = true
weight = 5.0

[builtins.clipboard]
avoid_line_breaks = true
exec = 'wl-copy'
image_height = 300.0
max_entries = 10.0
name = 'clipboard'
placeholder = 'Clipboard'
switcher_only = true
weight = 5.0

[builtins.commands]
icon = 'utilities-terminal'
name = 'commands'
placeholder = 'Commands'
switcher_only = true
weight = 5.0

[builtins.custom_commands]
icon = 'utilities-terminal'
name = 'custom_commands'
placeholder = 'Custom Commands'
weight = 5.0

[builtins.dmenu]
name = 'dmenu'
placeholder = 'Dmenu'
switcher_only = true
weight = 5.0

[builtins.emojis]
exec = 'wl-copy'
history = true
name = 'emojis'
placeholder = 'Emojis'
show_unqualified = false
switcher_only = true
typeahead = true
weight = 5.0

[builtins.finder]
concurrency = 8.0
icon = 'file'
ignore_gitignore = true
name = 'finder'
placeholder = 'Finder'
refresh = true
show_icon_when_single = true
switcher_only = true
use_fd = false
weight = 5.0

[builtins.runner]
generic_entry = false
history = true
icon = 'utilities-terminal'
name = 'runner'
placeholder = 'Runner'
refresh = true
typeahead = true
weight = 5.0

[builtins.ssh]
history = true
icon = 'preferences-system-network'
name = 'ssh'
placeholder = 'SSH'
refresh = true
switcher_only = true
weight = 5.0

[builtins.switcher]
name = 'switcher'
placeholder = 'Switcher'
prefix = '/'
weight = 5.0

[builtins.symbols]
after_copy = ''
history = true
name = 'symbols'
placeholder = 'Symbols'
switcher_only = true
typeahead = true
weight = 5.0

[builtins.websearch]
icon = 'applications-internet'
name = 'websearch'
placeholder = 'Websearch'
weight = 5.0

[[builtins.websearch.entries]]
name = 'Google'
url = 'https://www.google.com/search?q=%TERM%'

[[builtins.websearch.entries]]
name = 'DuckDuckGo'
switcher_only = true
url = 'https://duckduckgo.com/?q=%TERM%'

[[builtins.websearch.entries]]
name = 'Ecosia'
switcher_only = true
url = 'https://www.ecosia.org/search?q=%TERM%'

[[builtins.websearch.entries]]
name = 'Yandex'
switcher_only = true
url = 'https://yandex.com/search/?text=%TERM%'

[builtins.windows]
icon = 'view-restore'
name = 'windows'
placeholder = 'Windows'
show_icon_when_single = true
weight = 5.0

[events]
on_activate = ''
on_exit = ''
on_launch = ''
on_query_change = ''
on_selection = ''

[list]
dynamic_sub = true
keyboard_scroll_style = 'emacs'
max_entries = 50.0
placeholder = 'No Results'
show_initial_entries = true
single_click = true
visibility_threshold = 20.0

[search]
delay = 0.0
placeholder = 'Search...'
resume_last_query = false
